sudo: false
language: python
python:
  - "3.6"
git:
  depth: false

install:
  - pip install pipenv
  - pip install coveralls
  - pipenv install --dev

script:
  - pytest

after_success:
  # Hack to get around https://github.com/pytest-dev/pytest-cov/issues/242
  - pytest --cov=shallow_backup
  - coveralls

